name: build

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        description: interesting stuff
        options:
          - Ubuntu
          - macOS

jobs:
  scala3:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      TF_CPP_MIN_LOG_LEVEL: 3
      JAVA_OPTS: "-Xmx4096m -XX:+UseG1GC"
    name: Build and Test ${{ matrix.os }} ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Build With SBT
        run: sbt package
      - name: Test With SBT
        run: sbt test
